using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum EVENT_TYPE
{
    MURDERER_CREATE,SURVIVOR_CREATE,SURVIVOR_HIT, SURVIVOR_MOVE, SURVIVOR_STOP, SURVIVOR_GRAMCTRL, GRAM_START, GRAM_STOP, TIME_OVER,COUNT_DOWN, TIME_START
        ,SURVIVOR_DIE, GRAM_SUCCESS, SURVIVOR_GRAM_SUC, SURVIVOR_RADIOCTRL, SURVIVOR_RADIO_SUC, RADIO_SUCCESS, SURVIVOR_KEYCTRL, KEY_SUCCESS
        , SURVIVOR_KEYCTRL2, KEY_SUCCESS2, KEY_GET, KEY_GET_SUCCESS , KEY_GET2, KEY_GET_SUCCESS2, SURVIVOR_WIN
        ,GRAM_OPEN_KEY, RADIO_OPEN_KEY, B_RIGHT_BTN_POSSIBLE, B_RIGHT_BTN_IMPOSSIBLE
};

public interface IListener
{

    void OnEvent(EVENT_TYPE Evenet_Type, Component Sender, object Parm = null);

}